[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.16"
tokio = { version = "1.21.1", features = ["full"] }

# https://github.com/diesel-rs/diesel/blob/2.0.x/diesel/Cargo.toml
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "chrono", "uuid"] }
