drop table schools cascade;
drop table students cascade;
drop table teachers cascade;
drop table groups cascade;
drop table classes cascade;
drop table subjects cascade;
drop table grades cascade;
drop table tasks cascade;
drop table class_students cascade;